/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityOwnerRepoRouteImport } from './routes/city.$owner.$repo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityOwnerRepoRoute = CityOwnerRepoRouteImport.update({
  id: '/city/$owner/$repo',
  path: '/city/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city/$owner/$repo': typeof CityOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city/$owner/$repo': typeof CityOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city/$owner/$repo': typeof CityOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/city/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/city/$owner/$repo'
  id: '__root__' | '/' | '/city/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityOwnerRepoRoute: typeof CityOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$owner/$repo': {
      id: '/city/$owner/$repo'
      path: '/city/$owner/$repo'
      fullPath: '/city/$owner/$repo'
      preLoaderRoute: typeof CityOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityOwnerRepoRoute: CityOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
